Dimensionalillusions/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

#from Ehub.urls import *
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ehub.urls')),
    path('', include('Eblog.urls')),
    re_path(r'^', include('Msfx.urls')),
    re_path(r'^', include('Mvfx.urls')),

    path('', include('Mgraphics.urls')),
    # url(r'^',include('Mgraphics.urls')),

    # Custom Url
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="PasswordReset/password_reset.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="PasswordReset/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="PasswordReset/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="PasswordReset/password_reset_done.html"),
         name="password_reset_complete"),
]

# for acessing media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''    
    url(r'^',include('Eblog.urls')),
    path('',include('Edashboard.urls')),   
      
    path('',include('Msfx.urls')), 
    path('',include('Mvfx.urls')), 
    path('',include('Mweb.urls')),
    path('',include('Mtemplate.urls')),   
'''

Ehub/urls.py
from django.contrib import admin
from django.urls import path
from Ehub import views
from .views import *

app_name='Ehub'

urlpatterns = [
    path('', views.Home, name="home"),

    #Authetication 
    path('account/register/' , registeruser , name="register"),
    path('account/login/' , loginuser, name="login-user"),
    path('account/logout/',views.logoutUser, name="logout-user"),
    path('account/token/' , token_send , name="token_send"),
    path('account/success/' , success , name='success'),
    path('account/verify/<auth_token>' , verify , name="verify"),
    path('account/error/' , error_page , name="error"),

    path('search/', views.SearchEngine, name="search"),
    path('Contact_Us/', views.ContactApi, name="Contact_Us"),
    
    path('downloadpage/', views.PurchasedProducts, name="download"),

    path('user-cart/', views.YourCart, name="YourCart"),
    path('Checkout/', views.Checkout, name="Checkout"),
    path('Checkout/Add_Coupon/', views.addcouponcode, name="AddCoupon"),    
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),    
    
    path('process_order/', views.ProcessOrder, name="process_order"),    
        


]


templates/Sign-Up/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" type="image/png" sizes="50×20" href="{% static 'images/favicon.png'%}">
  <link rel="stylesheet" href="{% static 'css/FrontendCheatsheet.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  {% block title %}
  <title>DI | EA Verification</title>
  {% endblock %}

{% block style %}
  <style>
  </style>
{% endblock %}

</head>

{% block body %}

<body>
  <script src="{% static 'js/LinkerSheets.js' %}" type="text/javascript"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>

</body>
{% endblock %}

</html>

templates/Sign-Up/error.html
{% extends "Sign-Up/base.html"%}
{% block title %}
<title>DI | EA Verification | Error</title>
{% endblock %}
{% block body %}
<div class="container">
    <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center mt-5">Internal Sever Error</h3>

            <a href="/" class="btn btn-success">Back</a>

        </div>
    </div>
</div>
</div>


{% endblock %}

templates/Sign-Up/login.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    {% block title %}
    <title>DI | LoginPage</title>
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="50×20" href="{% static 'images/favicon.png'%}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/FrontendCheatsheet.css' %}">
    <title>Hello, world!</title>
</head>
{% block style %}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .errorbox {
        color: red;
        font-size: 1rem;
        text-align: center;
    }

    .successbox {
        color: rgb(255, 255, 255);
        font-size: 1rem;
        text-align: center;
    }

    body {
        background-image: url('{% static "images/lavaLogo.png" %}');
        background-size: cover;
        background-position: center;
        font-family: sans-serif;
    }

    input {
        width: 100%;
        color: white;
        display: block;
        outline: none;
        border: none;
        background-color: rgb(0, 0, 0, 0);
        border-bottom: 1px solid rgb(222, 222, 222);
    }

    .container-fluid {
        color: white;

        padding: 3rem;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .container-fluid .wrapper {
        width: 25rem;
        background-color: rgb(0, 0, 0, .7);
        padding: 4rem;
        padding-top: 6rem;
        padding-bottom: 6rem;
        border-radius: 4rem;
    }

    .wrapper p {
        display: inline;
    }

    .wrapper a {
        text-decoration: none;
    }


    .btn-custom {
        display: block;
        font-size: .9rem;
        border-radius: 2rem;
    }

    @media only screen and (max-width:551px) {
        .container-fluid .wrapper {
            background-color: rgb(0, 0, 0);
            padding: 3rem;
            padding-top: 3rem;
            padding-bottom: 3rem;
            border-radius: 2rem;
        }

        .errorbox {
            color: red;
            font-size: .8rem;
            text-align: center;
        }

        .successbox {
            color: rgb(255, 255, 255);
            font-size: .8rem;
            text-align: center;
        }

        .wrapper p {
            font-size: .8rem;
        }

        .wrapper a {
            font-size: .8rem;
        }

        .btn-custom {
            font-size: .8rem;
        }

        .errorlist {
            list-style-type: none;
            color: red;
            padding-right: 2rem;
        }

        .msgebox {

            font-size: .8rem;

        }

    }

    @media only screen and (max-width:391px) {
        .errorbox {
            color: red;
            font-size: .6rem;
            text-align: center;
        }

        .successbox {
            color: rgb(255, 255, 255);
            font-size: .6rem;
            text-align: center;
        }

        h3 {
            font-size: .9rem;
        }

        .container-fluid {
            color: white;
            font-size: .8rem;
        }

        .wrapper p {
            font-size: .7rem;
        }

        .wrapper a {
            font-size: .7em;
        }

        .container-fluid .wrapper {
            background-color: rgb(0, 0, 0);
            padding: 3rem;
            padding-top: 3rem;
            padding-bottom: 3rem;
            border-radius: 2rem;
        }

        .btn-custom {
            font-size: .8rem;

        }

        .msgebox {
            font-size: .7rem;
        }
    }
</style>
{% endblock %}

<body>


    <div class="container-fluid">
        <div class="wrapper mt-1">
            <h3 class="text-center pb-5"><strong>DI-LOGIN</strong> </h3>

            <form action="" autocomplete="on" method="post">
                {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="Enter your Username" autofocus required>
                <br>
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Enter your Password">
                <br><br>
                <input class="btn-lg btn-custom btn-primary" type="submit" value="Login">
                <br>

                {% if messages %}
                {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="errorbox">
                    <p1 id="messages">{{message}}!</p1>
                </div>
                <br>
                {% endif %}
                {% endfor %}

                {% endif %}

                {% if messages %}
                {% for message in messages %}
                {% if message.tags == "success" %}
                <div class="successbox">
                    <p1 id="messages">{{message}}!</p1>
                </div>
                <br>
                {% endif %}
                {% endfor %}
                {% endif %}
                <p>Don't have a DI account? </p> <a href="{% url 'Ehub:register' %}">Sign Up</a>
                <br><br>
                <p>Forget your password? </p> <a href="{% url 'reset_password' %}">Reset password</a>

            </form>

        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>


</body>

</html>

templates/Sign-Up/registration.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>DI | Registration Page </title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/FrontendCheatsheet.css' %}">
    <link rel="icon" type="image/png" sizes="50×20" href="{% static 'images/favicon.png'%}">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            background-image: url('{% static "images/lavaLogo.png" %}');
            background-size: cover;
            background-position: center;
            font-family: sans-serif;
        }

        input {
            width: 100%;
            color: white;
            display: block;
            outline: none;
            border: none;
            background-color: rgb(0, 0, 0, 0);
            border-bottom: 1px solid rgb(222, 222, 222);
        }

        input[type="submit"] {
            padding: .8rem;
            border-radius: 2rem;

        }

        .container-fluid {
            color: white;

            padding: 3rem;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .container-fluid .wrapper {
            width: 25rem;
            background-color: rgb(0, 0, 0, .7);
            padding: 3rem;
            padding-top: 5rem;
            padding-bottom: 6rem;
            border-radius: 4rem;
        }

        .wrapper p {
            display: inline;
        }

        .wrapper a {
            text-decoration: none;
        }


        .btn-custom {
            display: block;
            font-size: .9rem;
            border-radius: 2rem;
        }

        .errorlist {
            list-style-type: none;
            color: red;
            padding-right: 2rem;
        }

        .successbox {
            color: rgb(255, 255, 255);
            font-size: 1rem;
            text-align: center;
        }


        @media only screen and (max-width:551px) {
            .container-fluid .wrapper {
                background-color: rgb(0, 0, 0);
                padding: 3rem;
                padding-top: 3rem;
                padding-bottom: 3rem;
                border-radius: 2rem;
            }

            .errorbox {
                color: red;
                font-size: .8rem;
                text-align: center;
            }

            .successbox {
                color: rgb(255, 255, 255);
                font-size: .8rem;
                text-align: center;
            }

            .wrapper p {
                font-size: .8rem;
            }

            .wrapper a {
                font-size: .8rem;
            }

            .btn-custom {

                font-size: .8rem;

            }

            .msgebox {

                font-size: .8rem;

            }

        }

        @media only screen and (max-width:391px) {
            h3 {
                font-size: .9rem;
            }

            .errorbox {
                color: red;
                font-size: .6rem;
                text-align: center;
            }

            .successbox {
                color: rgb(255, 255, 255);
                font-size: .6rem;
                text-align: center;
            }

            .container-fluid {
                color: white;
                font-size: .8rem;
            }

            .wrapper p {
                font-size: .7rem;
            }

            .wrapper a {
                font-size: .7em;
            }

            .container-fluid .wrapper {
                background-color: rgb(0, 0, 0);
                padding: 3rem;
                padding-top: 3rem;
                padding-bottom: 3rem;
                border-radius: 2rem;
            }

            .btn-custom {
                font-size: .8rem;

            }

            .msgebox {
                font-size: .7rem;
            }
        }
    </style>
</head>

<body>

    <div class="container-fluid">
        <div class="wrapper">
            <h3 class="text-center pb-4"><strong>DI-REGISTER</strong> </h3>

            <form action="" method="post">
                {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="Enter your Username" autofocus required>
                <br>
                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="Enter a valid Email" required>
                <br>
                <label for="password1">Password</label>
                <input type="password" id="password" name="password1" placeholder="Enter a Password" required>
                <br>
                <label for="password2">Re-Enter Password</label>
                <input type="password" id="password2" name="password2" placeholder="Re-Enter the Password" required>
                <br>
                <input class="btn-primary" type="submit" name="submit" value="Sign Up">
                <br>

                {% if messages %}
                {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="errorbox">
                    <p1 id="messages">{{message}}!</p1>
                </div>
                <br>
                {% endif %}
                {% endfor %}

                {% endif %}

                {% if messages %}
                {% for message in messages %}
                {% if message.tags == "success" %}
                <div class="successbox">
                    <p1 id="messages">{{message}}!</p1>
                </div>
                <br>
                {% endif %}
                {% endfor %}
                {% endif %}

                <p>Already have an account? </p><a href="{% url 'Ehub:login-user' %}">Login</a>
                <br>
            </form>
        </div>
    </div>
    <script src="{% static 'js/LinkerSheets.js' %}" type="text/javascript"></script>
</body>

</html>

templates/Sign-Up/success.html
{% extends "Sign-Up/base.html"%}
{% block title %}
<title>DI | EA Verification | Sucess</title>
{% endblock %}
{% block style %}
<style>
i{
    color: greenyellow;
}
</style>
{% endblock %}
{% block body %}

<div class="global-container">
    <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center mt-4">Congratulations, Your account is verified. <i class="bi bi-check-circle"></i></h3>
            <div class="card-text text-center">
                Now,You can log in .
            </div>
            <div class="text-center mt-3">
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/Sign-Up/token_send.html
{% extends "Sign-Up/base.html"%}
{% load static %}

{% block title %}
<title>DI | EA Verification | TokenAuth</title>
{% endblock %}

{% block style %}
<style>
    .container{
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock %}

{% block body %}

<h2 class="text-center mt-4">From DI-Team</h2>
<div class="container">
    <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">We have sent an email to verify your Email and activate your DI Account.
            </h3>
            <div class="card-text text-center">
                Please check your mail.
            </div>


            <div class="container">
                <img src="{% static 'images/Gmail.jpg' %}">
                <a href="https://gmail.com/" target="_blank">

                    <button class="btn btn-primary">Open Gmail</button>
                </a>
            </div>

        </div>
    </div>
</div>


{% endblock %}