Dimensionalillusions/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

#from Ehub.urls import *
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ehub.urls')),
    path('', include('Eblog.urls')),
    re_path(r'^', include('Msfx.urls')),
    re_path(r'^', include('Mvfx.urls')),

    path('', include('Mgraphics.urls')),
    # url(r'^',include('Mgraphics.urls')),

    # Custom Url
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="PasswordReset/password_reset.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="PasswordReset/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="PasswordReset/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="PasswordReset/password_reset_done.html"),
         name="password_reset_complete"),
]

# for acessing media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''    
    url(r'^',include('Eblog.urls')),
    path('',include('Edashboard.urls')),   
      
    path('',include('Msfx.urls')), 
    path('',include('Mvfx.urls')), 
    path('',include('Mweb.urls')),
    path('',include('Mtemplate.urls')),   
'''

Ehub/urls.py
from django.contrib import admin
from django.urls import path
from Ehub import views
from .views import *

app_name='Ehub'

urlpatterns = [
    path('', views.Home, name="home"),

    #Authetication 
    path('account/register/' , registeruser , name="register"),
    path('account/login/' , loginuser, name="login-user"),
    path('account/logout/',views.logoutUser, name="logout-user"),
    path('account/token/' , token_send , name="token_send"),
    path('account/success/' , success , name='success'),
    path('account/verify/<auth_token>' , verify , name="verify"),
    path('account/error/' , error_page , name="error"),

    path('search/', views.SearchEngine, name="search"),
    path('Contact_Us/', views.ContactApi, name="Contact_Us"),
    
    path('downloadpage/', views.PurchasedProducts, name="download"),

    path('user-cart/', views.YourCart, name="YourCart"),
    path('Checkout/', views.Checkout, name="Checkout"),
    path('Checkout/Add_Coupon/', views.addcouponcode, name="AddCoupon"),    
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),    
    
    path('process_order/', views.ProcessOrder, name="process_order"),    
        


]


Ehub/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms  

from django.contrib.auth.models import User  #For importing User model of the django database
from .models import *

class CreateUserForm(UserCreationForm): #Newly defined CreateUserForm's gonna inherit UserCreationForm 
	class Meta:
		model = User     #User ia model in database
		fields =['username','email','password1','password2']  #write the fields exact  #field that will be shown in registration.html
  

Ehub/views.py
from .models import *
from Mvfx.models import *
from Msfx.models import *
from Mgraphics.models import *

from django.shortcuts import render, redirect, HttpResponse
import requests
from django.views.generic import View


from django.http import JsonResponse, response
import json              # data = json.loads(request.body)
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user, allowed_users, admin_only

from django.contrib.auth.admin import Group

import uuid
# for sending email
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail

from .forms import *

# Create your views here.


def Home(request):
    if request.user.is_authenticated:
        getprofile = request.user.profile
        # Imp note:-when payment is done of order a new order is created but no get from database
        order, created = Order.objects.get_or_create(
            profile=getprofile, complete=False)
        purchase, created = PurchasedProduct.objects.get_or_create(
            profile=getprofile, complete=False)

        getfreevfxproducts = FreeVfxProduct.objects.all()
        getpaidvfxproducts = PaidVfxProduct.objects.all()

        getfreesfxproducts = FreeSfxProduct.objects.all()
        getpaidsfxproducts = PaidSfxProduct.objects.all()

    else:
        getfreevfxproducts = FreeVfxProduct.objects.all()
        getpaidvfxproducts = PaidVfxProduct.objects.all()

        getfreesfxproducts = FreeSfxProduct.objects.all()
        getpaidsfxproducts = PaidSfxProduct.objects.all()

        order = {}

    context = {
        'order': order,
        'getfreevfxproducts': getfreevfxproducts,
        'getpaidvfxproducts': getpaidvfxproducts,

        'getfreesfxproducts': getfreesfxproducts,
        'getpaidsfxproducts': getpaidsfxproducts,

    }
    return render(request, 'frontend_base.html', context)


def ContactApi(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        title = request.POST['title']
        content = request.POST['content']
        if len(name) <= 2 and len(title) <= 4 and len(content) <= 9:
            messages.error(request, "Please fill the form correctly")
        else:
            instantcontact = Email(
                name=name, email=email, title=title, content=content)
            instantcontact.save()
            messages.success(
                request, "Your message has been successfully sent")

    return render(request, "E-HUB/contact.html")


def SearchEngine(request):
    if request.user.is_authenticated:
        getprofile = request.user.profile
        order, created = Order.objects.get_or_create(
            profile=getprofile, complete=False)
        TotalCartAmount = order.get_lightiningvfx_total+order.get_energyvfx_total+order.get_muzzleflashes_total+order.get_shockwaves_total+order.get_particles_total+order.get_environmentvfx_total+order.get_debrisandcracksvfx_total+order.get_lightiningsfx_total+order.get_energysfx_total+order.get_environmentalsfx_total+order.get_firesfx_total + \
            order.get_machinerysfx_total+order.get_weaponsfx_total+order.get_fightingsfx_total+order.get_landscapes_total+order.get_characters_total+order.get_opticallens_total + \
            order.get_audiopack_total+order.get_vfxpack_total+order.get_flimtransitionpack_total + \
            order.get_motiongraphicspack_total + \
            order.get_audiospectrum_total+order.get_lyricstemplate_total

    else:
        TotalCartAmount = 0
        order = {'get_cart_total': 0, 'get_cart_items': 0, 'shipping': False}

    query = request.GET['query']
    if len(query) > 78 or len(query) < 3 or len(query) == 0:
      # SPECIAL PACKS
        getfreesoundpacks = SoundPack.objects.none()
        getpaidsoundpacks = SoundPack.objects.none()

        TotalCount = countVfxandSfx+countSpecialPacksAndOthers+countGraphicsElements

    else:
        getpaidsoundpacks = SoundPack.objects.filter(
            name__icontains=query, type="PAID")
        getfreesoundpacks = SoundPack.objects.filter(
            name__icontains=query, type="FREE")

    # GRAPHICS ELEMENT
        getfreelandscapes = Landscapes.objects.filter(
            name__icontains=query, type="FREE")
        getpaidlandscapes = Landscapes.objects.filter(
            name__icontains=query, type="PAID")

        getfreecharacters = Characters.objects.filter(
            name__icontains=query, type="FREE")
        getpaidcharacters = Characters.objects.filter(
            name__icontains=query, type="PAID")

        TotalCount = countVfxandSfx+countSpecialPacksAndOthers+countGraphicsElements
    print(TotalCount)
    print(countVfxandSfx)
    print(countSpecialPacksAndOthers)
    params = {
        'countVfxandSfx': countVfxandSfx,

        'getpaidDebrisAndCrackVfx': getpaidDebrisAndCrackVfx,

        'query': query,
        'TotalCartAmount': TotalCartAmount,

    }
    return render(request, 'search.html', params)


def YourCart(request):
    if request.user.is_authenticated:
        getprofile = request.user.profile
        order, created = Order.objects.get_or_create(
            profile=getprofile, complete=False)

        # OTHERS
        rendervfxpaidproducts = order.orderpaidvfxproduct_set.all()
        rendersfxpaidproducts = order.orderpaidsfxproduct_set.all()
        rendergraphicspaidproducts = order.orderpaidgraphicsproduct_set.all()

    else:
        rendersfxpaidproducts = {}
        rendergraphicspaidproducts = {}
        rendervfxpaidproducts = {}

        order = {}

    context = {
        'rendervfxpaidproducts': rendervfxpaidproducts,
        'rendersfxpaidproducts': rendersfxpaidproducts,
        'rendergraphicspaidproducts': rendergraphicspaidproducts,
        'order': order,


    }
    # for displaying no of item in red circle of cart icon
    return render(request, 'E-HUB/cart.html', context)


def getcoupon(request, getcode):
    try:
        coupon = DiscountCoupon.objects.get(discountcode=getcode)
        return coupon
    except:
        messages.ERROR('Coupon doesnot exist')
        return redirect('Ehub:Checkout')


@login_required(login_url='login')
def addcouponcode(request):
    if request.user.is_authenticated:
        print('hello')
        if request.method == "POST":
            getcode = request.POST['discountcode']
            getprofile = request.user.profile
            # we are setting the customer value on authebnticating the user
            order, created = Order.objects.get_or_create(
                profile=getprofile, complete=False)
            order.discountcoupon = getcoupon(request, getcode)
            order.save()
            return redirect('Ehub:Checkout')


def Checkout(request):
    if request.user.is_authenticated:
        getprofile = request.user.profile
        order, created = Order.objects.get_or_create(
            profile=getprofile, complete=False)

        rendervfxpaidproducts = order.orderpaidvfxproduct_set.all()
        rendersfxpaidproducts = order.orderpaidsfxproduct_set.all()
        rendergraphicspaidproducts = order.orderpaidgraphicsproduct_set.all()
    else:
        rendersfxpaidproducts = {}
        rendergraphicspaidproducts = {}
        rendervfxpaidproducts = {}
        order = {}

    context = {
        # VFX
        'rendervfxpaidproducts': rendervfxpaidproducts,
        'rendersfxpaidproducts': rendersfxpaidproducts,
        'rendergraphicspaidproducts': rendergraphicspaidproducts,
        'order': order,

    }

    return render(request, 'E-HUB/checkout.html', context)


class KhaltiVerifyView(View):

    def get(self, request, *args, **kwargs):
        print('Initaiting Khalti Verificatiion...')
        transaction_id = datetime.datetime.now().timestamp()

        token = request.GET.get("token")
        amount = request.GET.get("amount")
        o_id = request.GET.get("order_id")
        getprofile = request.user.profile
        print(o_id)
        print(token, amount, o_id)

        url = "https://khalti.com/api/v2/payment/verify/"
        payload = {
            "token": token,
            "amount": amount
        }
        headers = {
            "Authorization": "Key test_secret_key_de01b0c1f02b48759df0953a0dcfc8f0"
        }

        order = Order.objects.get(profile=getprofile, complete=False)
        purchase = PurchasedProduct.objects.get(
            profile=getprofile, complete=False)

        orderpaidvfxproduct = OrderPaidVfxProduct.objects.filter(
            profile=getprofile, complete=False)
        orderpaidsfxproduct = OrderPaidSfxProduct.objects.filter(
            profile=getprofile, complete=False)

        response = requests.post(
            url, payload, headers=headers)  # sending data to url
        resp_dict = response.json()
        print(resp_dict.get('idx'))

        total = amount
        if resp_dict.get("idx"):
            if total == amount:
                success = True
                order.complete = True
                order.transaction_id = transaction_id
                order.save()

                purchase.complete = True
                purchase.transaction_id = transaction_id
                purchase.save()

            # VFX
                for x in orderpaidvfxproduct:
                    if total == float(order.grand_totalamount):
                        x.complete = True
                    x.save()

            # SFX
                for x in orderpaidsfxproduct:
                    if total == float(order.grand_totalamount):

templates/E-HUB/cart.html
{% extends 'frontend_base.html' %}
{% block title %}
<title>DI | Cart </title>
{% endblock %}
{% load static %}   
{% block body%}
	<div class="row g-0" style="background-color:#007bff ;">

		<div class="col-lg-12" style="color: white;">

			<div class="box-element" style="box-shadow:hsl(0, 0%, 0%)0 0 16px;
                 background-color:#000; border-radius:4px; padding :10px;">

				<br>

				<div>
					<a class="btn btn-primary"  style="float: right;" id="change-color" href="{% url 'Ehub:Checkout' %}">checkout &rarr;</a>
				</div>
				<br>
				<br>
			</div>

			<br class="gx-0">

			<div class="box-element" style="box-shadow:hsl(0, 0%, 1%) 0 0 30px;
                 background-color:#111111; border-radius:4px; padding :6px;">
				
				<div class="cart-row" style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;" >
					<div style="flex:2"><strong><h4>Products</h4></strong></div>
					<div style="flex:1"><strong><h4>Price</h4></strong></div>

					<div style="flex:1"><strong><h4>Remove</h4></strong></div>
				</div>

				{% for item in rendervfxpaidproducts %}   
				<div class="cart-row" style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;" >
					<div style="flex:2"><strong>{{ item.product}}</strong></div>
					<div style="flex:1"><strong> ${{ item.product.get_final_total|floatformat:2}}</strong></div>
					
					<div style="flex:1"><span><button type="button" data-product="{{item.product}}"  data-poid="{{item.id}}" data-pubid="{{item.published_by}}"  data-action="rmvpdt" class="chg-quantity btn btn-sm btn-danger Vfx-cart">Remove</button></div>
				</div>
				{% endfor %}

				{% for item in rendersfxpaidproducts %}   
				<div class="cart-row" style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;" >
					<div style="flex:2"><strong>{{ item.product}}</strong></div>
					<div style="flex:1"><strong> ${{ item.product.get_final_total|floatformat:2}}</strong></div>
					
					<div style="flex:1"><span><button type="button" data-product="{{item.product}}"  data-poid="{{item.id}}" data-pubid="{{item.published_by}}"  data-action="rmvpdt" class="chg-quantity btn btn-sm btn-danger Sfx-cart">Remove</button></div>
				</div>
				{% endfor %}

				{% for item in rendergraphicspaidproducts %}   
				<div class="cart-row" style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;" >
					<div style="flex:2"><strong>{{ item.product}}</strong></div>
					<div style="flex:1"><strong> ${{ item.product.get_final_total|floatformat:2}}</strong></div>
					
					<div style="flex:1"><span><button type="button" data-product="{{item.product}}"  data-poid="{{item.id}}" data-pubid="{{item.published_by}}"  data-action="rmvpdt" class="chg-quantity btn btn-sm btn-danger Graphics-cart">Remove</button></div>
				</div>
				{% endfor %}

				<br>
				<br>
				<br>

				<br>
				<br>
			</div>

			<br>
			<br>
			<br>
			
		</div>
	</div>
{% endblock body%}

templates/E-HUB/checkout.html
{% extends 'frontend_base.html' %}
{% block title %}
<title>DI | Checkout </title>
{% endblock %}
{% load static %}

{% block body%}
<style>

</style>
<div class="row g-0" style="background-color:#181818 ;">

	<div class="col-lg-8" style="background-color: black; border: 22px solid #181818;">
		<div class="box-element p-4" style="color: white;">
			<a class="btn btn-primary" style="margin: 20px;" href="{% url 'Ehub:YourCart' %}">&#x2190; Back to Your Cart</a>
			<hr>
			<h2>Summary:</h2>
			<hr style="background-color: white;">


			{% for item in rendervfxpaidproducts %}
			<div class="cart-row"
				style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;">

				<div style="flex:2">
					<p>{{item.product.name}}</p>
				</div>
				<div style="flex:1">
					<p>${{item.product.get_final_total|floatformat:2}}</p>
				</div>
				<div style="flex:1">
					<p>x{{item.quantity}}</p>
				</div>
			</div>
			{% endfor %}

			{% for item in rendersfxpaidproducts %}
			<div class="cart-row"
				style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;">

				<div style="flex:2">
					<p>{{item.product.name}}</p>
				</div>
				<div style="flex:1">
					<p>${{item.product.get_final_total|floatformat:2}}</p>
				</div>
				<div style="flex:1">
					<p>x{{item.quantity}}</p>
				</div>
			</div>
			{% endfor %}


			{% for item in rendergraphicspaidproducts %}
			<div class="cart-row"
				style="display:flex; align-items:flex-stretch; margin-bottom:10px; padding-bottom:20px ;border-bottom: 1px solid black ;">

				<div style="flex:2">
					<p>{{item.product.name}}</p>
				</div>
				<div style="flex:1">
					<p>${{item.product.get_final_total|floatformat:2}}</p>
				</div>
				<div style="flex:1">
					<p>x{{item.quantity}}</p>
				</div>
			</div>
			{% endfor %}			

			<hr>

			<h5 style="color: white;">TotalProducts: {{order.grand_totalquantity}}</h5>
			{% if order.discountcoupon %}
			<h5>Discount applied: {{order.discountcoupon.discount}} %</h5>
			{% endif %}
			<hr> 
			<h5>Total Amount: ${{order.grand_totalamount|floatformat:2}}</h5>
			<br>
		</div>
	</div>

	<br>
	<br>

	<div class="col-lg-3 p-2" style="background-color: black; border: 22px solid #181818;">

		<br>
		<div class="box-element " id="payment-info">
			<h4 class="text-center" style="color: white; font-family: poppins;">Payment Options</h4>
			<div class="khalti-container">
				<button class="btn khalti-btn" id="payment-button"><strong>Khalti</strong></button>
			</div>
			<br>
			<div id="paypal-button-container"></div>

			<form class="d-flex" action="{% url 'Ehub:AddCoupon' %}" method="POST">
				{% csrf_token %}
				<input class="form-control me-2" type="text" name="discountcode"  placeholder="Enter DiscountCode">
				<input type="submit" class= "btn btn-primary" value="Reedem">
			</form>

		</div>
		<br>
		<br>

	</div>

	<br>
	<br>

</div>

<!-- PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=AUpg7Hgv4nw9CDxWQjKj8AJF4bUTShD8dYs1zXAdLI8HgtQNZ9RuHpOtWfhdfcBrcZVrngZzf9MiRvDG&disable-funding=credit"></script>
<script>
	paypal.Buttons({
		style: {
			color: 'blue',
			shape: 'rect',
		},
		createOrder: function (data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: parseFloat(total).toFixed(2)
					}
				}]
			});
		},

		// Finalize the transaction(create paymnt)
		onApprove: function (data, actions) {
			return actions.order.capture().then(function (details) {
				submitFormData()
			});
		}

	}).render('#paypal-button-container');
</script>

<script type="text/javascript">

	//creating a total var that holds the total amount
	var total = '{{order.grand_totalamount}}'

	if (user != 'AnonymousUser') {
		document.getElementById('form-wrapper').classList.add("hidden");

		document.getElementById('payment-info').classList.remove("hidden");
	}

	var form = document.getElementById('form')
	csrftoken = form.getElementsByTagName('input')[0].value
	console.log('Newtoken generated', form.getElementsByTagName('input')[0].value)

	form.addEventListener('submit', function (e) {
		e.preventDefault()
		console.log('Form submitted...')
		document.getElementById('form-button').classList.add("hidden");
		document.getElementById('payment-info').classList.remove("hidden");
	})

	function submitFormData() {
		console.log('Initiating Payment...')

		var userFormData = {
			'name': null,
			'email': null,
			'total': total,
		}

		if (user == 'Anonymoususer') {
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}

		console.log('User Info:', userFormData)
		/*For verification  of process of order*/
		var url = '/process_order/'
		fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'X-CSRFToken': csrftoken,
			},
			body: JSON.stringify({
				'form': userFormData,
			}),
		})
			.then((response) => response.json())
			.then((data) => {
				console.log('Sucess:', data);
				alert('Transaction completed');
				window.location.href = "{% url 'Ehub:download' %}"

			})
	}
</script>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- Include the Khalti JavaScript SDK -->
<script>
	var config = {
		"publicKey": "test_public_key_95cae5a0974c43b1a6be964395ab4853",
		"productIdentity": "order_{{order.id}}",
		"productName": "order_{{order.id}}",
		"productUrl": "http://localhost:8000",
		"paymentPreference": [
			"KHALTI",
			"EBANKING",
			"MOBILE_BANKING",
			"CONNECT_IPS",
			"SCT",
		],
		"eventHandler": {
			onSuccess(payload) {

				axios.get("/khalti-verify/", {
					params: {
						"token": payload.token,
						"amount": payload.amount,
						"order_id": "{{order.id}}"
					}
				}).then(function (resp) {
					if (resp.data.success == true) {
						alert("Thanks. Payment Completed Successfully")
						window.location.href = "{% url 'Ehub:download' %}"
					} else {
						alert("Sorry. Error occurred")
						location.href = "{{request.build_absolute_uri}}"
					}
				})
			},

			onClose() {
				console.log('widget is closing');
			}
		}
	};
	var checkout = new KhaltiCheckout(config);
	var btn = document.getElementById("payment-button");
	btn.onclick = function () {
		// minimum transaction amount must be 10, i.e 1000 in paisa.
		checkout.show({ amount: {{ order.grand_totalamount | floatformat:2 }} *1000});
	}
</script>

...
{% endblock body %}

templates/E-HUB/contact.html
{% extends 'frontend_base.html' %}
{% block contactactive %} active {% endblock contactactive %}
{% block title %}
<title>DI | ContactUs </title>
{% endblock %}
{% block ActivateContact %}active{% endblock %}
{% block body %}
<div style="background-color: black;" class="word">
  <br><br>

  <div class="container" style="max-width:770px;">
  <div class="row">

    <div class="col-sm-12">
    <main>
      <br><br>
      <h2 class="text-center">Contact Us</h2>
      <br>

      <form action="{% url 'Contact_Us' %}" autocomplete="on" method="post">  
      {% csrf_token %}
        <div class="form-group textcolor">
          <label style="color: white;" for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" required autofocus>
          <br>
        </div>
      

          <label style="color: white;" for="email">Email address</label>
          <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
          <small  style="color: rgb(169, 169, 169);" id="emailHelp" class="form-text">You are requested to provide a Valid Email.</small>
          <br>

        <br>

        <div class="form-group textcolor">
          <label style="color: white;" for="title">Title:</label>
          <input type="text" class="form-control" id="title" name="title" required>
          <br>
        </div>
      


        <div class="form-group textcolor">
          <label style="color: white;" for="content">Description :</label>
          <textarea class="form-control" name="content" id="content" cols="30" rows="5" required></textarea>
          <br>
        </div>
      
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
        <br>
        <br>  <br><br>
      </form>
    </main>


    
    </div>
  </div>
  </div>

</div>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
  {% for message in messages %}
      {% if message.tags == "success" %}       
      swal("Message Sent Sucesfully");
      {% endif %}
  {% endfor %}
</script> 
{% endblock %}

templates/E-HUB/downloadpage.html
{% extends 'downloadbase.html' %}
{% block title %}
<title>DI |DownloadPage </title>
{% endblock %}
{% load static %}
{% block body %}

<div style="background-color: #000000; padding: 2rem;">
  <h2 class="text-center mb-0" style="background-color: #000000;">Welcome to DownloadPage</h2>
  <hr>
</div>

<div class="row">
  <div class="col-lg-12" style="color: white;">
    <div class="box-element" style="box-shadow:hsl(0, 0%, 0%)0 0 16px;
                 background-color:#000; padding :1rem;">
      <a class="btn rounded-3 btn-primary" href="{% url 'Ehub:home' %}">&#x2190;
        Go To Home</a>
    </div>

  </div>
</div>

<div class="jumbotron" style="background-color: black; margin: 0px;">
  <div class="album py-5 font-control">
    <div class="container">

      <div class="row" style="background-color: black;">

        {% for i in rendervfxpaidproducts %}
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 font-control">

          <div class="card mb-4 shadow-sm " style="background-color: #111111;">

            <div class="video">
              <video loop src="{{i.product.watermarkfreeproduct.url}}">
              </video>
            </div>

            <div class="card-body">
              <p class="card-text"><strong>{{i.name}}</strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{i.product.watermarkfreeproduct.url}}" download="">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Download</button>
                  </a>
                </div>
              </div>
            </div>

          </div>
        </div>
        {% endfor %}
        
        {% for i in rendersfxpaidproducts %}
        <div class="col-6 col-sm-6 col-md-4 col-lg-3">
          <div class="card mb-4 shadow-sm" style="background-color: #111111;">
            <audio style="height: 1.4rem;" controls>
              <source src="{{i.product.watermarkfreeproduct.url}}">
            </audio>
            <div class="card-body">
              <p class="card-text">{{i.product.name}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{i.product.watermarkfreeproduct.url}}" download="">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Download</button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        {% for i in rendergraphicspaidproducts %} 
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 font-control">

            <div class="card mb-4 shadow-sm " style="background-color: #111111;">
                <img src="{{i.product.watermarkfreeproduct.url}}" alt="" srcset="" width="100%" height="150">

                <div class="card-body">

                    <div class="card-body">
                      <p class="card-text text-center"><strong>{{i.name}}</strong></p>
                      <div class=" text-center align-items-center">
                        <div class="btn-group ">
                          <a href="{{i.product.watermarkfreeproduct.url}}" download="">
                          <button type="button" class="btn btn-sm btn-outline-secondary">Download</button>
                          </a>
                      </div>
                      </div>
                    </div>

                </div>

            </div>

        </div>
        {% endfor %}


      </div>
    </div>
  </div>
</div>
{% endblock %}